apiVersion: tekton.dev/v1
kind: PipelineRun

metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/danilo-gemoli/ComplianceAsCode-compliance-operator?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "master"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: foobar
    appstudio.openshift.io/component: compliance-as-code-compliance-operator-ed329
    pipelines.appstudio.openshift.io/type: build
  name: compliance-as-code-compliance-operator-ed329-on-pull-request
  namespace: testplatform-ci-tenant

spec:
  pipelineSpec:
    description: Run the AWS Serial e2e test

    tasks:
    - name: run-test
      # params:
      # - name: kubeconfigSecretRef
      #   value: $(tasks.provision-ephemeral-cluster.results.secretRef)
      taskSpec:
        # params:
        # - name: kubeconfigSecretRef
        #   type: string

        steps:
        - name: run-test
          image: registry.redhat.io/ubi9/go-toolset@sha256:3ce6311380d5180599a3016031a9112542d43715244816d1d0eabc937952667b
          # env:
          # - name: IMAGE_FROM_CI
          #   value: $(params.imageFromCI[0])
          script: |
            #!/usr/bin/env bash
            echo "body:"
            python -c 'import json; import sys; json.dump(json.loads("""{{ body.pull_request }}"""), sys.stdout)'
            echo ""
            echo "---"
            echo ""
            echo "headers:"
            python -c 'import json; import sys; json.dump(json.loads("""{{ headers }}"""), sys.stdout)'

    workspaces:
    - name: git-auth
      optional: true
    - name: netrc
      optional: true
  
  taskRunTemplate:
    serviceAccountName: build-pipeline-compliance-as-code-compliance-operator-ed329
  
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'

  timeouts:
    pipeline: 12h0m0s
    tasks: 6h0m0s
    finally: 6h0m0s

status: {}
